# Generated by Django 5.1.4 on 2025-03-10 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="analysis_images/%Y/%m/%d/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("image_width", models.IntegerField(blank=True, null=True)),
                ("image_height", models.IntegerField(blank=True, null=True)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待分析"),
                            ("processing", "分析中"),
                            ("completed", "已完成"),
                            ("failed", "分析失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_stego", models.BooleanField(default=False)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("analysis_time", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-upload_time"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stego_type", models.CharField(blank=True, max_length=50, null=True)),
                ("embedding_rate", models.FloatField(blank=True, null=True)),
                ("payload_size", models.IntegerField(blank=True, null=True)),
                ("detection_method", models.CharField(max_length=100)),
                ("confidence_score", models.FloatField()),
                ("analysis_duration", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_result",
                        to="analysis.imageanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "信息"), ("warning", "警告"), ("error", "错误")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="imageanalysis",
            index=models.Index(
                fields=["user", "upload_time"], name="analysis_im_user_id_197fa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imageanalysis",
            index=models.Index(fields=["status"], name="analysis_im_status_764760_idx"),
        ),
        migrations.AddIndex(
            model_name="imageanalysis",
            index=models.Index(
                fields=["is_stego"], name="analysis_im_is_steg_27d9eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["timestamp"], name="analysis_sy_timesta_da76c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(fields=["level"], name="analysis_sy_level_5dbe80_idx"),
        ),
    ]
